version: '3.1'

services:

  db:
    container_name: database
    image: mysql:5.5
    hostname: database
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: appuser
      MYSQL_PASSWORD: AppP@ssw0rd
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: RootP@ssw0rd

  java-app:
    container_name: app
    hostname: app
    build:
      context: ./build
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: appuser
      DB_PASSWORD: AppP@ssw0rd
      DB_IP: database
      DB_NAME: app

volumes:
  mysql_data:

